### ISSUE TITLE
Support Typescript

### ISSUE THREAD

**Issue by artis3n** [salmanm/num-words#13]
Would you consider supporting Typescript?

Using this in a Typescript project results in the following error:

```
S7016: Could not find a declaration file for module 'num-words'. '/<...>/node_modules/num-words/index.js' implicitly has an 'any' type.   Try `npm install @types/num-words` if it exists or add a new declaration (.d.ts) file containing `declare module 'num-words';`
```

I am not super familiar on how to do that myself, but I see many projects have type definitions under @types. The documentation for that appears to be <https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#publish-to-types>. [This page](https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html) also has some documentation on how to build in typescript types natively to your library.

This would be a convenience when using this with a Typescript project. I currently suppress the error with:

```ts
// @ts-ignore
import numWords from 'num-words'
```

**Comment by trangcongthanh** [comment]
I created PR #27 to solve your issue.

If you can't wait for it to get merged, you can create your local declaration to bypass the error from tsc.

1. Create a new file `src/types/num-words.d.ts`
2. Paste the content below:
```
declare module 'num-words' {
  function numWords(v: number): string
  export default numWords
}
```

**Comment by salmanm** [comment]
Fixed in https://github.com/salmanm/num-words/pull/27
