### ISSUE TITLE
It does not work on decimal digits.

### ISSUE THREAD

**Issue by jainprashul** [salmanm/num-words#2]
It is getting undefined on decimal digits upto 2digits

**Comment by yusy4code** [comment]
Here is one of my similar use case which I solved like this

```
const numWords = require('.')

let amount = process.argv[2] || 123.23
let amountArr = amount.toString().split('.')

console.log(`${amount} = ${numWords(amountArr[0])} Euros and ${numWords(amountArr[1])} cents`)
```

**Comment by gegobyte** [comment]
> Here is one of my similar use case which I solved like this
> 
> ```
> const numWords = require('num-words')
> 
> let amount = 123.23
> let amountArr = amount.toString().split('.')
> 
> console.log(`${amount} = ${numWords(amountArr[0])} Euros and ${numWords(amountArr[1])} cents`)
> ```

close #3

**Comment by salmanm** [comment]
I think the above solution is good enough. This library does not deal with any currency so it might not be good to select a currency keyword in the response.

An alternative would be to return an object like `{base: 'One', fraction: 'Twenty'}` and let user format using the currency they want. But not sure if that's gonna be any better than just doing it like how @gegobyte has shown above.
